#!/usr/bin/env bash
#The script to use while loop and if,elif, and else statements in combination

i=1
while ((i<=10))
do
if ((i==4))
then
echo "bad luck"
elif ((i==8));
then
echo "good luck"
else
echo "Best School"
fi
i=$((i+1))
done
