#!/usr/bin/env bash
#A script to use while loop with case statement

i=1
while ((i<=20))
do
case "$i" in
 4) 
  echo "bad luck from China"
   ;;
 9) 
  echo "bad luck from Japan"
   ;;
 17) 
  echo "bad luck from Italy"
   ;;
esac
((i+1))
echo "$i"
done
