#!/usr/bin/env bash
#A script to display time using while loop and head command for the first 70 lines

head -n 70 /loops_conditions_and_parsing/7-clock
hours=0
while ((hours<=12))
do
echo "$hours"
hours=$((hours+1))
minutes=1
while ((minutes<=59))
do
echo "$minutes"
minutes=$((minutes+1))
done
done
