#!/usr/bin/env bash
#A script to display time using while loop and head command for the first 70 lines

hours=0
head -n 70 /loops_conditions_and_parsing/7-clock
while ((hours<=12))
do
hours=$((hours+1))
minutes=1
while ((minutes<=59))
do
echo "$hours"
echo "$minutes"
minutes=$((minutes+1))
done
done
