#!/usr/bin/env bash
# A script to manage deamon

command="$1"

if [ -z "$command" ]; then
  echo "Usage: manage_my_process {start|stop|restart}"
  exit
fi

if [[ "$command" == "start" ]]; then
  ./manage_my_process &
  echo "$!" > /var/run/my_process.pid
  echo "manage_my_process started"

elif [[ "$command" == "stop" ]]; then
  sudo pkill -f './manage_my_process' &
  rm /var/run/my_process.pid &
  echo "manage_my_process stopped"

elif [[ "$command" == "restart" ]]; then
  "$0" stop >& /dev/null
  "$0" start >& /dev/null
  echo "manage_my_process restarted"

else
  echo "Usage: manage_my_process {start|stop|restart}"
fi
