#!/usr/bin/env bash
# A script to manage deamon

start() {
 ./manage_my_process &
  echo "$!" > /var/run/my_process.pid
  echo "manage_my_process started"
}
  stop() {
 sudo pkill -f './manage_my_process' &
 rm /var/run/my_process.pid &
  echo "manage_my_process stopped"
}
  restart() {
sudo pkill manage_my_process &
rm /var/run/my_process.pid &
./manage_my_process &
  echo "$!" > /var/run/my_process.pid
  echo "manage_my_process restarted"
}

  if (( $# == 1 )) || (( $# == 2 )); then
	  echo "Usage: manage_my-process {start|stop|restart}"
else
	case $1 in
		"start")
		start
		;;
	"stop")
	stop
	;;
"restart")
restart
;;
esac
fi
